//! The laws a declared interface curve obeys (stormlight/server#97).
//!
//! A [`UiTrack`] is sampled every frame, by an interpreter that has no idea what
//! the numbers mean, on data that arrived from a mod. So what is pinned here is
//! not "the curve looks nice" but the four things the client is allowed to assume:
//!
//!   - **A segment lands.** Whatever shape an author asked for, progress `0` is the
//!     earlier key exactly and progress `1` is the later key exactly. A curve that
//!     overshot its own keys would put a widget somewhere no key named, and one
//!     that undershot would leave an entrance permanently unfinished.
//!   - **A sample is always one of the declared values or between two of them.** The
//!     interpreter writes what it is handed straight onto a node, so a track may
//!     never produce a number outside the range its author declared.
//!   - **It ends where the playback rule says.** [`Playback::Once`] holds its last
//!     key forever, [`Playback::Loop`] returns to its first, and
//!     [`Playback::PingPong`] is a mirror about the end — pinned as the *relation*
//!     between two times rather than as a value at one, which is what makes it a
//!     property rather than an echo of the implementation.
//!   - **Nothing panics and nothing is NaN**, for any elapsed time at all, including
//!     the negative and infinite ones a clock should never produce and a hostile
//!     descriptor is under no obligation to avoid.

use bolero::{TypeGenerator, check};
use stormlight_mod_abi::ui_anim::{Ease, Playback, Shape, UiKey, UiProperty, UiTrack, UiTrigger};

extern crate alloc;
use alloc::vec::Vec;

/// One of the four tangents, from a generated byte — the ABI's own enums carry no
/// generator, so a scenario picks them the way every other descriptor test does.
fn ease(pick: u8) -> Ease {
    match pick % 4 {
        0 => Ease::Linear,
        1 => Ease::Slow,
        2 => Ease::Fast,
        _ => Ease::Step,
    }
}

fn playback(pick: u8) -> Playback {
    match pick % 3 {
        0 => Playback::Once,
        1 => Playback::Loop,
        _ => Playback::PingPong,
    }
}

fn property(pick: u8) -> UiProperty {
    match pick % 4 {
        0 => UiProperty::TranslateX,
        1 => UiProperty::TranslateY,
        2 => UiProperty::Scale,
        _ => UiProperty::Opacity,
    }
}

/// A generated key: whole-ish times and values, so a scenario reaches the exact
/// boundaries (a key *at* another key's time, a flat segment) that the interesting
/// bugs live on.
#[derive(Debug, TypeGenerator)]
struct Key {
    gap: u8,
    value: i8,
    arrive: u8,
    leave: u8,
}

#[derive(Debug, TypeGenerator)]
struct Scenario {
    keys: Vec<Key>,
    playback: u8,
    property: u8,
    /// Milliseconds, so the sampled moment lands inside and outside the track.
    at: u16,
}

impl Scenario {
    /// The declared track: times accumulate from the generated gaps, so they are
    /// non-decreasing by construction and a zero gap is a legal duplicate.
    fn track(&self) -> UiTrack {
        let mut time = 0.0;
        let keys = self
            .keys
            .iter()
            .take(8)
            .map(|key| {
                time += f32::from(key.gap) / 64.0;
                UiKey {
                    time,
                    value: f32::from(key.value),
                    arrive: ease(key.arrive),
                    leave: ease(key.leave),
                }
            })
            .collect();
        UiTrack {
            property: property(self.property),
            on: UiTrigger::Built,
            playback: playback(self.playback),
            keys,
        }
    }

    fn elapsed(&self) -> f32 {
        f32::from(self.at) / 1000.0
    }
}

/// Every shape an author can name.
fn shapes() -> impl Iterator<Item = Shape> {
    let all = [Ease::Linear, Ease::Slow, Ease::Fast, Ease::Step];
    all.into_iter()
        .flat_map(move |leave| all.into_iter().map(move |arrive| Shape { leave, arrive }))
}

#[test]
fn every_shape_lands_on_both_of_its_keys() {
    for shape in shapes() {
        assert!(
            shape.ease(0.0).abs() < 1e-6,
            "{shape:?} starts away from the key it leaves, so a widget jumps the \
             moment its curve begins",
        );
        assert!(
            (shape.ease(1.0) - 1.0).abs() < 1e-6,
            "{shape:?} ends away from the key it arrives at, so an entrance never \
             finishes where it was declared to",
        );
    }
}

#[test]
fn no_shape_leaves_the_segment_it_is_shaping() {
    check!().with_type::<u16>().for_each(|&step| {
        let u = f32::from(step) / f32::from(u16::MAX);
        for shape in shapes() {
            let eased = shape.ease(u);
            assert!(
                (0.0..=1.0).contains(&eased),
                "{shape:?} at {u} left its own segment ({eased}), which puts a \
                 widget at a value no key declared",
            );
        }
    });
}

#[test]
fn a_shape_is_total_over_whatever_it_is_handed() {
    for shape in shapes() {
        for u in [f32::NAN, f32::INFINITY, f32::NEG_INFINITY, -5.0, 12.0] {
            let eased = shape.ease(u);
            assert!(
                eased.is_finite() && (0.0..=1.0).contains(&eased),
                "{shape:?} produced {eased} from {u}: a clock that hiccuped would \
                 put a NaN into a layout",
            );
        }
    }
}

#[test]
fn a_sample_is_never_outside_the_values_its_author_declared() {
    check!().with_type::<Scenario>().for_each(|s| {
        let track = s.track();
        if track.keys.is_empty() {
            return;
        }
        let low = track.keys.iter().map(|k| k.value).fold(f32::INFINITY, f32::min);
        let high = track.keys.iter().map(|k| k.value).fold(f32::NEG_INFINITY, f32::max);
        for at in [0.0, s.elapsed(), track.duration(), track.duration() * 3.0] {
            let value = track.sample(at);
            assert!(
                value.is_finite() && (low - 1e-4..=high + 1e-4).contains(&value),
                "a track sampled at {at} read {value}, outside the {low}..={high} \
                 its keys declared",
            );
        }
    });
}

#[test]
fn a_track_is_total_over_any_clock_at_all() {
    check!().with_type::<Scenario>().for_each(|s| {
        let track = s.track();
        for at in [f32::NAN, f32::INFINITY, f32::NEG_INFINITY, -1.0, f32::MAX] {
            let value = track.sample(at);
            assert!(value.is_finite(), "a track read {value} at {at} and would write it to a node");
        }
    });
}

#[test]
fn an_empty_track_reads_as_the_widget_exactly_as_declared() {
    check!().with_type::<(u8, u16)>().for_each(|&(pick, at)| {
        let property = property(pick);
        let track =
            UiTrack { property, on: UiTrigger::Built, playback: Playback::Once, keys: Vec::new() };
        assert!(
            (track.sample(f32::from(at) / 100.0) - property.rest()).abs() < f32::EPSILON,
            "a track with nothing in it moved the widget away from where it was \
             declared, instead of leaving it alone",
        );
        assert!(track.duration().abs() < f32::EPSILON, "a track with no keys has no length");
    });
}

#[test]
fn a_held_track_stays_where_it_arrived_and_a_repeating_one_comes_back() {
    check!().with_type::<Scenario>().for_each(|s| {
        let mut track = s.track();
        let Some(&last) = track.keys.last() else { return };
        let first = track.keys[0];
        if track.duration() <= 0.0 {
            return;
        }
        let long = track.duration() * 4.0;

        track.playback = Playback::Once;
        assert!(
            (track.sample(long) - last.value).abs() < 1e-4,
            "a one-shot did not hold its last key, so an entrance drifts after it lands",
        );

        // A loop is periodic: the same phase reads the same value one whole
        // duration later. Stated as a relation, so it holds for every curve
        // rather than for the one this scenario happened to generate.
        track.playback = Playback::Loop;
        let phase = track.duration() * 0.25;
        assert!(
            (track.sample(phase) - track.sample(phase + track.duration())).abs() < 1e-3,
            "a looping track read differently one cycle later, so a pulse drifts",
        );
        assert!(
            (track.sample(track.duration() * 2.0) - first.value).abs() < 1e-3,
            "a loop did not come back to its first key at the top of a cycle",
        );

        // A ping-pong is a mirror about its end: as far past the turn as before it
        // reads the same, which is exactly what makes it bounce rather than jump.
        track.playback = Playback::PingPong;
        let before = track.duration() - phase;
        let after = track.duration() + phase;
        assert!(
            (track.sample(before) - track.sample(after)).abs() < 1e-3,
            "a ping-pong was not symmetric about its turn, so it ticks instead of \
             breathing",
        );
    });
}

#[test]
fn a_step_holds_the_earlier_value_until_the_moment_it_does_not() {
    // The one shape that does not pass through the middle: a flicker is a value
    // that is wrong for a while and then right, never a value on its way.
    check!().with_type::<u8>().for_each(|&step| {
        let u = f32::from(step) / f32::from(u8::MAX);
        for shape in [
            Shape { leave: Ease::Step, arrive: Ease::Linear },
            Shape { leave: Ease::Linear, arrive: Ease::Step },
        ] {
            let eased = shape.ease(u);
            assert!(
                eased == 0.0 || (u >= 1.0 && eased == 1.0),
                "a stepped segment interpolated ({eased} at {u}) instead of holding",
            );
        }
    });
}
