//! Authoring an interface that moves (stormlight/server#97).
//!
//! The pdk adds no semantics here — the curve is the ABI's — so what is pinned is
//! that the authoring path cannot quietly lose or corrupt what an author wrote:
//!
//!   - **A widget starts still.** Every constructor hands back a widget with no
//!     tracks and no catch-up, so a HUD that never heard of this issue is exactly
//!     the HUD it was before the ABI grew a time axis.
//!   - **Declaring a curve changes the curve and nothing else** — the same
//!     one-property rule every other setter on this trait obeys.
//!   - **Tracks accumulate in declaration order**, because a widget may drive
//!     several properties and which track is "the one for this property" is decided
//!     by that order.
//!   - **What the pdk builds is what the host accepts**: the curve an author writes
//!     with these helpers passes the ABI's own validation, or the authoring layer
//!     is shipping mods that cannot load.

use bolero::{TypeGenerator, check};
use stormlight_mod_abi::ids::Slot;
use stormlight_mod_abi::ui::{
    Layout, RootVisibility, Strip, Style, SummonGate, UiRoot, UiSubject, Widget, WidgetKind,
    WidgetState,
};
use stormlight_mod_abi::ui_anim::{Ease, Playback, Shape, UiProperty, UiTrack, UiTrigger};
use stormlight_mod_sdk::ui::{KeyExt, WidgetExt, ability_slot, bar, icon, key, panel, text, track};

/// One of the four tangents, from a generated byte.
fn ease(pick: u8) -> Ease {
    match pick % 4 {
        0 => Ease::Linear,
        1 => Ease::Slow,
        2 => Ease::Fast,
        _ => Ease::Step,
    }
}

#[derive(Debug, TypeGenerator)]
struct Scenario {
    property: u8,
    trigger: u8,
    playback: u8,
    arrive: u8,
    leave: u8,
    /// Tenths of a second.
    length: u8,
    from: i8,
    to: i8,
    /// Which kind the curve is declared on — a curve is style, so it must be
    /// declarable on anything a mod can put on screen.
    kind: u8,
}

impl Scenario {
    fn track(&self) -> UiTrack {
        track(
            match self.property % 4 {
                0 => UiProperty::TranslateX,
                1 => UiProperty::TranslateY,
                2 => UiProperty::Scale,
                _ => UiProperty::Opacity,
            },
            match self.trigger % 3 {
                0 => UiTrigger::Built,
                1 => UiTrigger::State(WidgetState::Hovered),
                _ => UiTrigger::Hidden,
            },
            match self.playback % 3 {
                0 => Playback::Once,
                1 => Playback::Loop,
                _ => Playback::PingPong,
            },
            vec![
                key(0.0, f32::from(self.from)).leaving(ease(self.leave)),
                key(f32::from(self.length) / 10.0, f32::from(self.to)).arriving(ease(self.arrive)),
            ],
        )
    }

    fn widget(&self) -> Widget {
        match self.kind % 4 {
            0 => panel(vec![]),
            1 => text("ready"),
            2 => bar(stormlight_mod_abi::ui::ValueBinding::Health),
            _ => icon("mod://pack/plate.png"),
        }
    }
}

#[test]
fn every_constructor_hands_back_a_widget_that_stands_still() {
    for widget in [
        panel(vec![]),
        text("hp"),
        bar(stormlight_mod_abi::ui::ValueBinding::Health),
        icon("mod://pack/plate.png"),
        ability_slot(Slot(0), "Q"),
    ] {
        assert!(
            widget.style.anim.is_empty(),
            "a widget arrived from the pdk already animating, so a still HUD would \
             have to switch its animation off",
        );
        assert!(
            widget.style.transition.is_none(),
            "a widget arrived with a catch-up nobody declared",
        );
    }
}

#[test]
fn declaring_a_curve_changes_the_curve_and_nothing_else() {
    check!().with_type::<Scenario>().for_each(|s| {
        let base = s.widget().color([1.0, 0.5, 0.25, 1.0]);
        let declared = s.track();
        let after = base.clone().animated(declared.clone());

        assert_eq!(
            after.style.anim,
            vec![declared],
            "the curve on the widget is not the one the author wrote",
        );
        assert_eq!(
            Style { anim: base.style.anim.clone(), ..after.style.clone() },
            base.style,
            "declaring a curve disturbed another property of the style",
        );
        assert_eq!(after.layout, base.layout, "declaring a curve moved the widget");
        assert_eq!(after.kind, base.kind, "declaring a curve changed what the widget is");
    });
}

#[test]
fn tracks_keep_the_order_they_were_declared_in() {
    check!().with_type::<Scenario>().for_each(|s| {
        let first = s.track();
        let mut second = s.track();
        second.property = UiProperty::Opacity;
        let widget = panel(vec![]).animated(first.clone()).animated(second.clone());
        assert_eq!(
            widget.style.anim,
            vec![first, second],
            "a second curve replaced the first instead of joining it, so a widget \
             can only ever drive one property",
        );
    });
}

#[test]
fn a_catch_up_is_exactly_what_was_asked_for() {
    check!().with_type::<Scenario>().for_each(|s| {
        let seconds = f32::from(s.length) / 10.0;
        let shape = Shape { leave: ease(s.leave), arrive: ease(s.arrive) };
        let widget = bar(stormlight_mod_abi::ui::ValueBinding::Health).transition(seconds, shape);
        let declared = widget.style.transition.expect("a declared catch-up is on the widget");
        assert!(
            (declared.seconds - seconds).abs() < f32::EPSILON && declared.shape == shape,
            "the catch-up on the widget is not the one the author declared",
        );
        assert!(declared.is_usable(), "the pdk built a catch-up the host would refuse");
    });
}

#[test]
fn what_the_pdk_builds_is_what_the_host_loads() {
    check!().with_type::<Scenario>().for_each(|s| {
        let widget =
            s.widget().animated(s.track()).transition(f32::from(s.length) / 10.0, Shape::default());
        let root = UiRoot {
            name: "hud".into(),
            when: RootVisibility::Always,
            summon: SummonGate::Ignored,
            subject: UiSubject::LocalPlayer,
            strip: Strip::default(),
            root: Widget {
                name: "root".into(),
                layout: Layout::default(),
                style: Style::default(),
                kind: WidgetKind::Panel { children: vec![widget] },
            },
        };
        assert_eq!(
            root.validate(),
            Ok(()),
            "the authoring path built an interface the host refuses to load",
        );
    });
}
